services:
  pomodoro-api:
    build: .
    container_name: pomodoro-api
    volumes:
      - ./server.js:/app/server.js
      - ../classes/PomodoroTimer.js:/app/PomodoroTimer.js
    ports:
      - "3000:3000"
    restart: unless-stopped